# Variables
@baseUrl = http://localhost:3333

# Health check
GET {{baseUrl}}/health

###

# Get rooms
GET {{baseUrl}}/rooms

###

POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Sala de teste",
  "description": "Essa é uma sala de teste"
}

###

GET {{baseUrl}}/rooms/a6732832-9805-4da4-f281-fa7773aff23b/questions